# Generated by Django 3.2.12 on 2022-03-20 19:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import github.MainClass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('forks_count', models.IntegerField()),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('license', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
            },
        ),
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=39, unique=True)),
                ('bio', models.CharField(blank=True, max_length=160, null=True)),
                ('blog', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hireable', models.BooleanField()),
                ('html_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('public_repos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'GitHub User',
                'verbose_name_plural': 'GitHub Users',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('file_extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=256)),
                ('by', models.CharField(choices=[('NAME', 'Username'), ('LOC', 'Location'), ('LANG', 'Language'), ('PROF', 'Profession')], default='PROF', max_length=4)),
            ],
            bases=(models.Model, github.MainClass.Github),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.githubuser')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('repositories', models.ManyToManyField(to='search.GitHubRepository')),
                ('skills', models.ManyToManyField(to='search.Skill')),
                ('users', models.ManyToManyField(to='search.GitHubUser')),
            ],
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='search.githubuser'),
        ),
    ]
