# Generated by Django 3.2.12 on 2022-03-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=256)),
                ('by', models.CharField(choices=[('NAME', 'Username'), ('BIO', 'Bio'), ('COMP', 'Company'), ('EMPL', 'Employability'), ('LOC', 'Location'), ('LANG', 'Language'), ('PROF', 'Profession')], default='PROF', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='profession',
            name='person',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='professions',
        ),
        migrations.AddField(
            model_name='profession',
            name='repositories',
            field=models.ManyToManyField(to='search.GitHubRepository'),
        ),
        migrations.AddField(
            model_name='profession',
            name='skills',
            field=models.ManyToManyField(to='search.Skill'),
        ),
        migrations.AddField(
            model_name='profession',
            name='users',
            field=models.ManyToManyField(to='search.GitHubUser'),
        ),
    ]
