# Generated by Django 3.2.12 on 2022-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
